apiVersion: v1
kind: Service
metadata:
  name: net-iface
spec:
  selector:
    app: net-iface
  type: NodePort
  ports:
    - port: 80
      nodePort: 30001
      targetPort: http


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-iface
spec:
  replicas: 4
  selector:
    matchLabels:
      app: net-iface
  
  template:
    metadata:
      labels:
        app: net-iface
    spec:
      containers:
      - name: net-iface
        image: lussa/net-iface:0.2
        resources:
          limits:
            memory: "75Mi"
            cpu: "50m"
        ports:
          - name: http
            containerPort: 80
